spring:
  application:
    name: config-server
  cloud:
    config:
      uri:
      - 

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "threaddump"
  endpoint:
    health:
      show-details: always
      group:
        custom:
          include:
            - diskSpace
            - ping
          show-components: always
          show-details: always
info: 
  application:
    name: E-Comm-Config-Server
    description: A demo application with custom info
    version: @project.version@ # Dynamically pull from Maven/Gradle project version
  environment:
    enabled: true # Exposes environment properties
  custom:
    message: Custom info!
    author: Niteesh Nadiger

