services:
  eureka-server:
    image: "niteeshnadiger/eureka-server:v1"
    container_name: eureka-server
    ports:
      - "8761:8761"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ecomnetwork
  config-server:
    image: "niteeshnadiger/config-server:v1"
    container_name: config-server
    ports:
      - "8888,:8888"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ecomnetwork

  api-gateway:
    image: "niteeshnadiger/api-gateway:v1"
    container_name: api-gateway
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ecomnetwork
  order-service:
    image: "niteeshnadiger/order-service:v1"
    container_name: order-service
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ecomnetwork
  inventory-service:
    image: "niteeshnadiger/inventory-service:v1"
    container_name: inventory-service
    ports:
      - "8085:8085"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ecomnetwork
  payment-service:
    image: "niteeshnadiger/payment-service:v1"
    container_name: payment-service
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ecomnetwork
networks:
  ecomnetwork:
    driver: "bridge"